# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nn_andrej_zero_to_hero',
                'doc_host': 'https://dimasmufid.github.io',
                'git_url': 'https://github.com/dimasmufid/nn_andrej_zero_to_hero',
                'lib_path': 'nn_andrej_zero_to_hero'},
  'syms': {'nn_andrej_zero_to_hero.core': {'nn_andrej_zero_to_hero.core.foo': ('core.html#foo', 'nn_andrej_zero_to_hero/core.py')}}}
